name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc mlflow tensorflow scikit-learn pandas numpy

    - name: Initialize DVC
      run: |
        dvc init --no-scm
        dvc config core.no_scm true

    - name: Run AI Agent
      run: |
        python scripts/ai_agent.py

    - name: Commit DVC changes
      run: |
        git add .
        git config --global user.email "vanhai11203@gmail.com"
        git config --global user.name "vanhai1231"
        git commit -m "AI Agent: Cập nhật dữ liệu và mô hình" || echo "No changes to commit"
        git push