name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc mlflow tensorflow scikit-learn pandas numpy
          dvc --version
          python -m pip list | grep -E 'dvc|mlflow|tensorflow|scikit-learn|pandas|numpy'

      - name: Check directory structure
        run: |
          ls -R .

      - name: Initialize DVC (no-scm mode)
        run: |
          dvc init --no-scm -f
          dvc config core.no_scm true

      - name: Pull data from DVC (nếu có)
        run: |
          dvc pull data/raw/sample_data.csv.dvc || echo "Không tìm thấy remote hoặc file DVC - bỏ qua"

      - name: Tạo file sample_data.csv nếu chưa tồn tại
        run: |
          if [ ! -f data/raw/sample_data.csv ]; then
            mkdir -p data/raw
            echo "feature,label" > data/raw/sample_data.csv
            echo "1,0" >> data/raw/sample_data.csv
            echo "2,1" >> data/raw/sample_data.csv
            echo "3,0" >> data/raw/sample_data.csv
            echo "4,1" >> data/raw/sample_data.csv
            echo "5,0" >> data/raw/sample_data.csv
            echo "Đã tạo file sample_data.csv"
          else
            echo "Đã tồn tại sample_data.csv, không cần tạo"
          fi

      - name: Run AI Agent
        env:
          PYTHONPATH: ${PYTHONPATH}:.
        run: |
          echo "Bắt đầu chạy AI Agent..."
          python scripts/ai_agent.py

      - name: Commit & push DVC changes (nếu có)
        run: |
          git config --global user.email "vanhai11203@gmail.com"
          git config --global user.name "vanhai1231"
          git add .
          git commit -m "AI Agent: Cập nhật dữ liệu và mô hình" || echo "Không có thay đổi mới"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify completion
        if: always()
        run: |
          echo "Pipeline hoàn tất lúc $(date -u) UTC"
          echo "Kiểm tra thư mục models/"
          ls -lh models/ || echo "Không tìm thấy models/"
